### PR TITLE
unrestrict transport layer jackson for mcp

### LINKED ISSUE #455: MCP server fails to initialize due to Unrecognized field "form"
When connecting to Matchbox (v4.0.16) as an MCP server from Visual Studio Code (Copilot), the server fails to initialize and throws a Jackson deserialization error.

ERROR [nio-8080-exec-2] eamableServerTransportProvider:499: Failed to deserialize message: Unrecognized field "form" (class io.modelcontextprotocol.spec.McpSchema$ClientCapabilities$Elicitation), not marked as ignorable (0 known properties: ])
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: io.modelcontextprotocol.spec.McpSchema$InitializeRequest["capabilities"]->io.modelcontextprotocol.spec.McpSchema$ClientCapabilities["elicitation"]->io.modelcontextprotocol.spec.McpSchema$ClientCapabilities$Elicitation["form"])

The client (VS Code) is sending the following structure in the initialize request:
```
"capabilities":{
  "elicitation": {
    "form": {}
   }
}
```

### PR DESCRIPTION
**Pull request by yoliyu**
Added .objectMapper() configuration to the MCP server to ignore unknown properties, ensuring compatibility with newer versions

.objectMapper(new ObjectMapper().configure(com.fasterxml.jackson.databind.DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false))

## Summary by Sourcery

Bug Fixes:
- Prevent MCP server from failing on incoming messages that contain unknown JSON properties in the transport payload.

### CODE REVIEW

File: matchbox-server/src/main/java/ca/uhn/fhir/jpa/starter/mcp/McpServerConfig.java [hunk 1]
```diff
@@ -61,7 +61,7 @@ public HttpServletStreamableServerTransportProvider servletSseServerTransportPro
 		return HttpServletStreamableServerTransportProvider.builder()
 				.disallowDelete(false)
 				.mcpEndpoint(SSE_MESSAGE_ENDPOINT)
-				.objectMapper(new ObjectMapper())
+				.objectMapper(new ObjectMapper().configure(com.fasterxml.jackson.databind.DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false))
```
Comment (qligier) [inline matchbox-server/src/main/java/ca/uhn/fhir/jpa/starter/mcp/McpServerConfig.java]:
```suggestion
				.objectMapper(new ObjectMapper().configure(FAIL_ON_UNKNOWN_PROPERTIES, false))
```

Please use imports to make the code more readable.

**Review by qligier — APPROVED** [review]

**Review by oliveregger — CHANGES_REQUESTED** [review]
thx, can you update docs/changelog.md with the PR that the issue #455 will be closed with this?
